export const ApiMessage = {
  otpsentsuccessfully: 'Otp Sent SuccessFully',
  loginverify: 'Login Verify SuccessFully',
  verifyotp: 'Otp Verify SucessFully',
  userverify: 'Verify User SuccessFully',
  setuser: 'Set Profile SuccessFully',
  updateProfile: 'Profile Update SuccessFully',
  registerSuceess: 'Register SuccessFully',
  addreview: 'Review added successfully',
  likeunlike: 'review Liked SuccessFully',
  likeun: 'review Unliked SuccessFully',
  validotpenter: 'Please enter valid Otp',
  logoutmessage: 'Logout Successfuly',
  likeloginerror: 'Please login to like the review!',
  eligibilityloginerror: 'Please login to eligibility resgister!',
  namecharactererror: 'Name ensure this value has at most 26 characters',
  internalServerError: 'Something Went Wrong',
  serviceUnavailable: 'Service Unavailable',
  mobileNumberError: 'Please enter the valid phone number',
  mobileNumberZeroErr: 'Please Check number do not type 0 number',
  pancardValidError: 'Please enter the valid PAN number',
  EmailValidError: 'Please enter a valid email',
  linkError: 'Do not enter any link',
  letterNameErr: 'Please enter a valid name containing only letters.',
  termsAndConditionContent: 'By clicking here, I acknowledge that I have reviewed and understood the',
  otpContent: 'Please enter OTP send on your mobile number',
  otpValidError: 'Please enter the valid OTP',
  MaxCountError: 'Maximum 1000 characters allowed.'
}
