export const ContactUS = {
  locicon: '/assets/locationicon.svg',
  callicon: '/assets/callcontact.svg',
  emailicon: '/assets/email.svg',
  mapfram: '/assets/mapfram.svg',
  meettitle: 'Meet at',
  calltitle: 'Call on',
  emailtitle: 'Email on',
  emailtitleprofile: 'Email us at',
  meetsub:
    'First Floor, Plot No 3/1, Attic Smart Square Complex, Above 3M Care & LBB, 100 Feet Rd, Binnamangala, Stage 1, Indiranagar, Bengaluru, Karnataka - 560038, India',
  callnumber: '+91 7412933933',
  calltime: 'Mon - Sat (9.30 AM - 6.00 PM)',
  email: 'customer@banksathi.com',
  anytime: '(Anytime 24x7)',
  address :'Address :',
  address_temp :'Address 2 :',
  address_field_temp: 'FIRST FLOOR, H NO-RZ 1/1, INDRA PARK, NEAR SHIV MANDIR, Uttam Nagar, West Delhi, Delhi, 110059',
  callnumber_temp: '91-01414046172',
  phone : 'Phone :',
  mail : 'Mail :',
  address_2:'FIRST FLOOR, H NO-RZ 1/1, INDRA PARK, NEAR SHIV MANDIR, Uttam Nagar, West Delhi, Delhi, 110059',
  phone_2:'91-01414046172',
}
