export const ListingfilterData = {
  rewards: 'Best of Rewards Cards',
  card: 'Axis Bank MY Zone Credit Card',
  Personalcard: 'Personal Loans',
  fees: 'Annual Fees',
  image: '/assets/listingCradfilter.svg',
  logoimg: '/assets/footer-Logo.svg',
  helpimg: '/assets/help-circle.svg',
  ratingtitle: 'BankSathi Rating',
  money: '₹ 300/-',
  based: ' Dining - Shopping - Movie',
  recommended: 'Minimum Credit Score Required',
  none: 'None',
  future: 'Feature',
  shopping: 'Shopping, Rewards..',
  compare: 'Add to Compare',
  details: 'View Details',
  joiningfees: 'Joining Fees',
  anualdetail: '1st Year Fee ₹500',
  joingdetail: '1st Year Fee Free',
  recommendedetail: '690-850',
  complimentary: 'Buy 1 Get 1 Movie Tickets on Paytm',
  sonyliv: 'Get 40% off on food delivery at Swiggy ',
  edge: '20% off at 4000+ partner restaurants in India',
  upto: 'Get Flat ₹600 off at AJIO, on minimum spends of ₹2000 ',
  restoff: '20% off at 4000+ partner restaurants in India',
  apllynow: 'Apply now',
  checkelig: 'Check Eligibility',
  offertype: 'reward Credit',
  rating: '4.9',
  bankType: 'hdfc',
  features: 'Features',
  welcomeoffer: 'Welcome Offer',
  eligibledata: 'Eligible',
  wloffersony: 'SonyLiv Premium 1 year subscription worth ₹999 ',
  wlofferatoff: ' ₹ 600 off at AJIO, on minimum spends of ₹ 2000',
  wlofferswiggy: '40% off on Swiggy',
  wlofferairport: '4 Complimentary Airport Lounge Access',
  wlofferticket: 'Buy 1 Get 1 Movie Tickets on Paytm ',
  min_bal_open_ac:'Minimum Balance to Open Account',
  month_bal:'Minimum Monthly Balance',
  interest_rate:'Interest Rate',
  view_more : 'View more'
}

export const Listingfilterbox = [
  {
    id: 1,
    slug: 'slug1',
    rewards: 'Best of Rewards Cards',
    card: 'Axis Bank MY Zone Credit Card',
    Personalcard: 'Personal Loans',
    fees: 'Annual Fees',
    image: '/assets/listingCradfilter.svg',
    logoimg: '/assets/footer-Logo.svg',
    helpimg: '/assets/help-circle.svg',

    ratingtitle: 'BankSathi Rating',
    money: '₹ 300/-',
    based: ' Dining - Shopping - Movie',
    recommended: 'Recommended Credit Score',
    none: 'None',
    future: 'Feature',
    shopping: 'Shopping, Rewards..',
    compare: 'Add to Compare',
    details: 'View Details',
    joiningfees: 'Joining Fees',
    anualdetail: '1st Year Fee ₹500',
    joingdetail: '1st Year Fee Free',
    recommendedetail: '690-850',
    complimentary: 'Buy 1 Get 1 Movie Tickets on Paytm',
    sonyliv: 'Get 40% off on food delivery at Swiggy ',
    edge: '20% off at 4000+ partner restaurants in India',
    upto: 'Get Flat ₹600 off at AJIO, on minimum spends of ₹2000 ',
    restoff: '20% off at 4000+ partner restaurants in India',
    apllynow: 'Apply now',
    checkelig: 'Check Eligibility',
    offertype: 'reward Credit',
    rating: '4.9',
    bankType: 'hdfc',
    features: 'Features',
    welcomeoffer: 'Welcome Offer',
    wloffersony: 'SonyLiv Premium 1 year subscription worth ₹999 ',
    wlofferatoff: ' ₹ 600 off at AJIO, on minimum spends of ₹ 2000',
    wlofferswiggy: '40% off on Swiggy',
    wlofferairport: '4 Complimentary Airport Lounge Access',
    wlofferticket: 'Buy 1 Get 1 Movie Tickets on Paytm '
  },
  {
    id: 2,
    slug: 'slug2',
    rewards: 'Best of Rewards Cards',
    card: 'Mojo Platinum Credit card',
    Personalcard: 'Personal Loans',
    fees: 'Annual Fees',
    image: '/assets/recome-filter-card-mojo.svg',
    helpimg: '/assets/help-circle.svg',

    logoimg: '/assets/footer-Logo.svg',
    ratingtitle: 'BankSathi Rating',
    recommended: 'Recommended Credit Score',
    money: '₹ 500/-',
    based: ' Dining - Shopping - Movie',
    none: 'None',
    future: 'Feature',
    shopping: 'Shopping, Rewards..',
    compare: 'Add to Compare',
    details: 'View Details',
    joiningfees: 'Joining Fees',
    anualdetail: '1st Year Fee ₹500',
    joingdetail: '1st Year Fee Free',
    recommendedetail: '690-850',
    complimentary: 'Buy 1 Get 1 Movie Tickets on Paytm',
    sonyliv: 'Get 40% off on food delivery at Swiggy ',
    edge: '20% off at 4000+ partner restaurants in India',
    upto: 'Get Flat ₹600 off at AJIO, on minimum spends of ₹2000 ',
    restoff: '20% off at 4000+ partner restaurants in India',
    apllynow: 'Apply now',
    checkelig: 'Check Eligibility',
    rating: '4.9',
    offertype: 'student Credit',
    bankType: 'hdfc',
    features: 'Features',
    welcomeoffer: 'Welcome Offer',
    wloffersony: 'SonyLiv Premium 1 year subscription worth ₹999 ',
    wlofferatoff: ' ₹ 600 off at AJIO, on minimum spends of ₹ 2000',
    wlofferswiggy: '40% off on Swiggy',
    wlofferairport: '4 Complimentary Airport Lounge Access',
    wlofferticket: 'Buy 1 Get 1 Movie Tickets on Paytm '
  },
  {
    id: 3,
    slug: 'slug3',
    rewards: 'Best of Rewards Cards',
    card: 'Royale Signature Credit Card',
    Personalcard: 'Personal Loans',
    fees: 'Annual Fees',
    image: '/assets/recome-filter-black-kotak.svg',
    logoimg: '/assets/footer-Logo.svg',
    helpimg: '/assets/help-circle.svg',

    ratingtitle: 'BankSathi Rating',
    money: '₹ 600/-',
    based: ' Dining - Shopping - Movie',
    recommended: 'Recommended Credit Score',
    none: 'None',
    future: 'Feature',
    shopping: 'Shopping, Rewards..',
    compare: 'Add to Compare',
    details: 'View Details',
    joiningfees: 'Joining Fees',
    anualdetail: '1st Year Fee ₹500',
    joingdetail: '1st Year Fee Free',
    recommendedetail: '690-850',
    complimentary: 'Buy 1 Get 1 Movie Tickets on Paytm',
    sonyliv: 'Get 40% off on food delivery at Swiggy ',
    edge: '20% off at 4000+ partner restaurants in India',
    upto: 'Get Flat ₹600 off at AJIO, on minimum spends of ₹2000 ',
    restoff: '20% off at 4000+ partner restaurants in India',
    apllynow: 'Apply now',
    checkelig: 'Check Eligibility',
    rating: '4.9',
    offertype: 'Travel Credit',
    bankType: 'ICICI Bank',
    features: 'Features',
    welcomeoffer: 'Welcome Offer',
    wloffersony: 'SonyLiv Premium 1 year subscription worth ₹999 ',
    wlofferatoff: ' ₹ 600 off at AJIO, on minimum spends of ₹ 2000',
    wlofferswiggy: '40% off on Swiggy',
    wlofferairport: '4 Complimentary Airport Lounge Access',
    wlofferticket: 'Buy 1 Get 1 Movie Tickets on Paytm '
  },
  {
    id: 4,
    slug: 'slug4',
    rewards: 'Best of Rewards Cards',
    card: 'Mojo Platinum Credit card',
    Personalcard: 'Personal Loans',
    fees: 'Annual Fees',
    image: '/assets/recome-filter-card-mojo.svg',
    logoimg: '/assets/footer-Logo.svg',
    helpimg: '/assets/help-circle.svg',

    ratingtitle: 'BankSathi Rating',
    money: '₹ 400/-',
    based: ' Dining - Shopping - Movie',
    recommended: 'Recommended Credit Score',
    none: 'None',
    future: 'Feature',
    shopping: 'Shopping, Rewards..',
    compare: 'Add to Compare',
    details: 'View Details',
    joiningfees: 'Joining Fees',
    anualdetail: '1st Year Fee ₹500',
    joingdetail: '1st Year Fee Free',
    recommendedetail: '690-850',
    complimentary: 'Buy 1 Get 1 Movie Tickets on Paytm',
    sonyliv: 'Get 40% off on food delivery at Swiggy ',
    edge: '20% off at 4000+ partner restaurants in India',
    upto: 'Get Flat ₹600 off at AJIO, on minimum spends of ₹2000 ',
    restoff: '20% off at 4000+ partner restaurants in India',
    apllynow: 'Apply now',
    checkelig: 'Check Eligibility',
    rating: '4.9',
    bankType: 'ICICI Bank',
    features: 'Features',
    welcomeoffer: 'Welcome Offer',
    wloffersony: 'SonyLiv Premium 1 year subscription worth ₹999 ',
    wlofferatoff: '₹ 600 off at AJIO, on minimum spends of ₹ 2000',
    wlofferswiggy: '40% off on Swiggy',
    wlofferairport: '4 Complimentary Airport Lounge Access',
    wlofferticket: 'Buy 1 Get 1 Movie Tickets on Paytm '
  },
  {
    id: 5,
    slug: 'slug5',
    rewards: 'Best of Rewards Cards',
    card: 'Royale Signature Credit Card',
    Personalcard: 'Personal Loans',
    fees: 'Annual Fees',
    image: '/assets/recome-filter-black-kotak.svg',
    logoimg: '/assets/footer-Logo.svg',
    helpimg: '/assets/help-circle.svg',

    ratingtitle: 'BankSathi Rating',
    money: '₹ 400/-',
    based: ' Dining - Shopping - Movie',
    recommended: 'Recommended Credit Score',
    none: 'None',
    future: 'Feature',
    shopping: 'Shopping, Rewards..',
    compare: 'Add to Compare',
    details: 'View Details',
    joiningfees: 'Joining Fees',
    anualdetail: '1st Year Fee ₹500',
    joingdetail: '1st Year Fee Free',
    recommendedetail: '690-850',
    complimentary: 'Buy 1 Get 1 Movie Tickets on Paytm',
    sonyliv: 'Get 40% off on food delivery at Swiggy ',
    edge: '20% off at 4000+ partner restaurants in India',
    upto: 'Get Flat ₹600 off at AJIO, on minimum spends of ₹2000 ',
    restoff: '20% off at 4000+ partner restaurants in India',
    apllynow: 'Apply now',
    checkelig: 'Check Eligibility',
    rating: '4.9',
    bankType: 'ICICI Bank',
    features: 'Features',
    welcomeoffer: 'Welcome Offer',
    wloffersony: 'SonyLiv Premium 1 year subscription worth ₹999 ',
    wlofferatoff: ' ₹ 600 off at AJIO, on minimum spends of ₹ 2000',
    wlofferswiggy: '40% off on Swiggy',
    wlofferairport: '4 Complimentary Airport Lounge Access',
    wlofferticket: 'Buy 1 Get 1 Movie Tickets on Paytm '
  }
]

export const CompareCardBoxData = {
  id: 1,
  slug: 'slug1',
  creditscore: 'Credit Score',
  card: 'Axis Bank MY Zone Credit Card',
  Personalcard: 'Personal Loans',
  fees: 'Annual Fee',
  anualfees: '0',
  image: '/assets/listingCradfilter.svg',
  closeicon: '/assets/closeIcon.svg',
  ratingtitle: 'BankSathi Rating',
  helpimg: '/assets/help-circle.svg',
  money: '₹ 300/-',
  based: ' Dining - Shopping - Movie',
  recommended: 'Recommended Credit Score',
  none: 'None',
  future: 'Features',
  rewardrate: 'Reward Rate',
  compare: 'Add to Compare',
  details: 'View Details',
  joiningfees: 'Joining Fees',
  anualdetail: '1st Year Fee ₹500',
  joingdetail: '1st Year Fee Free',
  recommendedetail: '690-850',
  featureticket: 'Buy 1 Get 1 Movie Tickets on Paytm',
  featuretswiggy: 'Get 40% off on food delivery at Swiggy',
  featuretrest: '20% off at 4000+ partner restaurants in India',
  featuretajio: 'Get Flat ₹600 off at AJIO, on minimum spends of ₹2000 ',
  apllynow: 'Apply now',
  checkelig: 'Check Eligibility',
  offertype: 'Reward Rate',
  rating: '4.9',
  bankType: 'hdfc',
  rewardsub: 'Earn unlimited 2% cash back',
  rewardpersentage: '2%',
  apr: 'APR',
  ratingtitle: 'Rating',
  loungeaccess: 'Domestic Lounge access',
  benefits: 'Benefits',
  productdetails: 'Product details',
  welcomeoffer: 'Welcome Offer'
}

export const CompareCardBox = [
  {
    id: 1,
    slug: 'slug1',
    creditscore: 'Credit Score: 690-850',
    card: 'Axis Bank MY Zone Credit Card',
    Personalcard: 'Personal Loans',
    fees: 'Annual Fee',
    anualfees: '0',
    image: '/assets/listingCradfilter.svg',
    closeicon: '/assets/closeIcon.svg',
    helpimg: '/assets/help-circle.svg',

    ratingtitle: 'BankSathi Rating',
    money: '₹ 300/-',
    based: ' Dining - Shopping - Movie',
    recommended: 'Recommended Credit Score',
    none: 'None',
    future: 'Features',
    rewardrate: 'Reward Rate',
    compare: 'Add to Compare',
    details: 'View Details',
    joiningfees: 'Joining Fees',
    anualdetail: '1st Year Fee ₹500',
    joingdetail: '1st Year Fee Free',
    recommendedetail: '690-850',
    featureticket: 'Buy 1 Get 1 Movie Tickets on Paytm',
    featuretswiggy: 'Get 40% off on food delivery at Swiggy',
    featuretrest: '20% off at 4000+ partner restaurants in India',
    featuretajio: 'Get Flat ₹600 off at AJIO, on minimum spends of ₹2000 ',
    apllynow: 'Apply now',
    checkelig: 'Check Eligibility',
    offertype: 'Reward Rate',
    rating: '4.9',
    bankType: 'hdfc',
    rewardsub: 'Earn unlimited 2% cash back',
    rewardpersentage: '2%'
  },
  {
    id: 2,
    slug: 'slug2',
    creditscore: 'Credit Score: 690-850',
    card: 'Mojo Platinum Credit card',
    Personalcard: 'Personal Loans',
    fees: 'Annual Fee',
    anualfees: '200',
    image: '/assets/recome-filter-card-mojo.svg',
    closeicon: '/assets/closeIcon.svg',
    ratingtitle: 'BankSathi Rating',
    recommended: 'Recommended Credit Score',
    helpimg: '/assets/help-circle.svg',

    money: '₹ 500/-',
    based: ' Dining - Shopping - Movie',
    none: 'None',
    future: 'Features',
    rewardrate: 'Reward Rate',
    compare: 'Add to Compare',
    details: 'View Details',
    joiningfees: 'Joining Fees',
    anualdetail: '1st Year Fee ₹500',
    joingdetail: '1st Year Fee Free',
    recommendedetail: '690-850',
    featureticket: '4 complimentary lounge access within India in a calender year',
    featuretswiggy: '1% fuel surcharge waiver up to ₹500 per month on fuel transactions between ₹400 to ₹4,000',
    apllynow: 'Apply now',
    checkelig: 'Check Eligibility',
    rating: '4.9',
    offertype: 'student Credit',
    bankType: 'hdfc',
    rewardsub: 'Get 5% cash back on every day purchase',
    rewardpersentage: '5%'
  },
  {
    id: 3,
    slug: 'slug3',
    creditscore: 'Credit Score: 690-850',
    card: 'Royale Signature Credit Card',
    Personalcard: 'Personal Loans',
    fees: 'Annual Fee',
    anualfees: '500',
    image: '/assets/recome-filter-black-kotak.svg',
    closeicon: '/assets/closeIcon.svg',
    helpimg: '/assets/help-circle.svg',

    ratingtitle: 'BankSathi Rating',
    recommended: 'Recommended Credit Score',
    money: '₹ 500/-',
    based: ' Dining - Shopping - Movie',
    none: 'None',
    future: 'Features',
    rewardrate: 'Reward Rate',
    compare: 'Add to Compare',
    details: 'View Details',
    joiningfees: 'Joining Fees',
    anualdetail: '1st Year Fee ₹500',
    joingdetail: '1st Year Fee Free',
    recommendedetail: '690-850',
    featureticket: 'Earn accelerated 5% Fuel Points on spends at IndianOil outlets, Groceries and Bill payments',
    apllynow: 'Apply now',
    checkelig: 'Check Eligibility',
    rating: '4.9',
    offertype: 'student Credit',
    bankType: 'hdfc',
    rewardsub: 'Get 10% cash back on Uber eats',
    rewardpersentage: '5%'
  }
]
export const CompareCardBoxMobile = [
  {
    id: 1,
    slug: 'slug1',
    creditscore: 'Credit Score: 690-850',
    card: 'Axis Bank MY Zone Credit Card',
    Personalcard: 'Personal Loans',
    fees: 'Annual Fee',
    anualfees: '0',
    image: '/assets/listingCradfilter.svg',
    closeicon: '/assets/closeIcon.svg',
    helpimg: '/assets/help-circle.svg',

    ratingtitle: 'BankSathi Rating',
    money: '₹ 300/-',
    based: ' Dining - Shopping - Movie',
    recommended: 'Recommended Credit Score',
    none: 'None',
    future: 'Features',
    rewardrate: 'Reward Rate',
    compare: 'Add to Compare',
    details: 'View Details',
    joiningfees: 'Joining Fees',
    anualdetail: '1st Year Fee ₹500',
    joingdetail: '1st Year Fee Free',
    recommendedetail: '690-850',
    featureticket: 'Buy 1 Get 1 Movie Tickets on Paytm',
    featuretswiggy: 'Get 40% off on food delivery at Swiggy',
    featuretrest: '20% off at 4000+ partner restaurants in India',
    featuretajio: 'Get Flat ₹600 off at AJIO, on minimum spends of ₹2000 ',
    apllynow: 'Apply now',
    checkelig: 'Check Eligibility',
    offertype: 'Reward Rate',
    rating: '4.9',
    bankType: 'hdfc',
    rewardsub: 'Earn unlimited 2% cash back',
    rewardpersentage: '2%'
  },
  {
    id: 2,
    slug: 'slug2',
    creditscore: 'Credit Score: 690-850',
    card: 'Mojo Platinum Credit card',
    Personalcard: 'Personal Loans',
    fees: 'Annual Fee',
    anualfees: '200',
    image: '/assets/recome-filter-card-mojo.svg',
    closeicon: '/assets/closeIcon.svg',
    ratingtitle: 'BankSathi Rating',
    helpimg: '/assets/help-circle.svg',

    recommended: 'Recommended Credit Score',
    money: '₹ 500/-',
    based: ' Dining - Shopping - Movie',
    none: 'None',
    future: 'Features',
    rewardrate: 'Reward Rate',
    compare: 'Add to Compare',
    details: 'View Details',
    joiningfees: 'Joining Fees',
    anualdetail: '1st Year Fee ₹500',
    joingdetail: '1st Year Fee Free',
    recommendedetail: '690-850',
    featureticket: '4 complimentary lounge access within India in a calender year',
    featuretswiggy: '1% fuel surcharge waiver up to ₹500 per month on fuel transactions between ₹400 to ₹4,000',
    apllynow: 'Apply now',
    checkelig: 'Check Eligibility',
    rating: '4.9',
    offertype: 'student Credit',
    bankType: 'hdfc',
    rewardsub: 'Get 5% cash back on every day purchase',
    rewardpersentage: '5%'
  }
]

export const calCulatorJsonCard = [
  {
    image: '/assets/listingCradfilter.svg',
    cardName: 'Axis Bank MY Zone Credit Card',
    cardSubTilte: 'Flat 30% off on using Axis Bank Credit and Debit Cards'
  },
  {
    image: '/assets/listingCradfilter.svg',
    cardName: 'Axis Bank MY Zone Credit Card',
    cardSubTilte: 'Flat 30% off on using Axis Bank Credit and Debit Cards'
  },
  {
    image: '/assets/listingCradfilter.svg',
    cardName: 'Axis Bank MY Zone Credit Card',
    cardSubTilte: 'Flat 30% off on using Axis Bank Credit and Debit Cards'
  },
  {
    image: '/assets/listingCradfilter.svg',
    cardName: 'Axis Bank MY Zone Credit Card',
    cardSubTilte: 'Flat 30% off on using Axis Bank Credit and Debit Cards'
  },
  {
    image: '/assets/listingCradfilter.svg',
    cardName: 'Axis Bank MY Zone Credit Card',
    cardSubTilte: 'Flat 30% off on using Axis Bank Credit and Debit Cards'
  },
  {
    image: '/assets/listingCradfilter.svg',
    cardName: 'Axis Bank MY Zone Credit Card',
    cardSubTilte: 'Flat 30% off on using Axis Bank Credit and Debit Cards'
  }
]
