export const SavingListCards = {
  bankName: 'ICICI',
  annual_fee: 1,
  rewards: 'Best of Rewards Cards',
  daily_txn_limit_online: 1000000,
  card: 'Kotak Mahindra Savings Account',
  Personalcard: 'Personal Loans',
  avg_mon_bal: 10000,
  InterestRate: 'Interest Rate',
  image: '/assets/listingCradfilter.svg',
  logoimg: '/assets/footer-Logo.svg',
  helpimg: '/assets/help-circle.svg',
  ratingtitle: 'BankSathi Rating',
  money: '₹ 300/-',
  based: ' Dining - Shopping - Movie',
  monthlybalance: 'Minimum monthly balance',
  none: 'None',
  future: 'Feature',
  shopping: 'Shopping, Rewards..',
  compare: 'Add to Compare',
  details: 'View Details',
  balanceOpenAcc: 'Minimum Balance to Open A/c',
  balanceOpendetail: '5000',
  InterestRatedetail: '4%',
  monthlybalancedetail: '50000',
  complimentary: 'Buy 1 Get 1 Movie Tickets on Paytm',
  sonyliv: 'Get 40% off on food delivery at Swiggy ',
  edge: '20% off at 4000+ partner restaurants in India',
  upto: 'Get Flat ₹600 off at AJIO, on minimum spends of ₹2000 ',
  restoff: '20% off at 4000+ partner restaurants in India',
  apllynow: 'Apply now',
  checkelig: 'Check Eligibility',
  offertype: 'reward Credit',
  rating: 4.9,
  atm_with_limit_fpm: '1000000',
  bankType: 'hdfc',
  features: 'Features',
  welcomeoffer: 'Welcome Offer',
  eligibledata: 'Eligible',
  wloffersony: 'SonyLiv Premium 1 year subscription worth ₹999 ',
  wlofferatoff: ' ₹ 600 off at AJIO, on minimum spends of ₹ 2000',
  wlofferswiggy: '40% off on Swiggy',
  wlofferairport: '4 Complimentary Airport Lounge Access',
  wlofferticket: 'Buy 1 Get 1 Movie Tickets on Paytm ',
  AccountsavingTitle: 'Savings Account  ',
  rate_of_interest: 7.5,
  joining_fee: 0,
  DebitCardTitle: 'Debit Card Facilities  '
}

export const SavingCardListAll = [
  {
    id: 1,
    bankName: 'ICICI',
    annual_fee: 2,
    rewards: 'Best of Rewards Cards',
    daily_txn_limit_online: 10000,
    card: 'Kotak Mahindra Savings Account',
    Personalcard: 'Personal Loans',
    avg_mon_bal: 10000,
    InterestRate: 'Interest Rate',
    image: '/assets/listingCradfilter.svg',
    logoimg: '/assets/footer-Logo.svg',
    helpimg: '/assets/help-circle.svg',
    cardLogo: '/assets/kotak-logo.svg',
    ratingtitle: 'BankSathi Rating',
    money: '₹ 300/-',
    based: ' Dining - Shopping - Movie',
    monthlybalance: 'Minimum monthly balance',
    none: 'None',
    future: 'Feature',
    shopping: 'Shopping, Rewards..',
    compare: 'Add to Compare',
    details: 'View Details',
    balanceOpenAcc: 'Minimum Balance to Open A/c',
    balanceOpendetail: '5000',
    InterestRatedetail: '4%',
    monthlybalancedetail: '50000',
    complimentary: 'Buy 1 Get 1 Movie Tickets on Paytm',
    sonyliv: 'Get 40% off on food delivery at Swiggy ',
    edge: '20% off at 4000+ partner restaurants in India',
    upto: 'Get Flat ₹600 off at AJIO, on minimum spends of ₹2000 ',
    restoff: '20% off at 4000+ partner restaurants in India',
    apllynow: 'Apply now',
    checkelig: 'Check Eligibility',
    offertype: 'reward Credit',
    rating: 4.9,
    atm_with_limit_fpm: '1000000',
    bankType: 'hdfc',
    features: 'Features',
    welcomeoffer: 'Welcome Offer',
    eligibledata: 'Eligible',
    wloffersony: 'SonyLiv Premium 1 year subscription worth ₹999 ',
    wlofferatoff: ' ₹ 600 off at AJIO, on minimum spends of ₹ 2000',
    wlofferswiggy: '40% off on Swiggy',
    wlofferairport: '4 Complimentary Airport Lounge Access',
    wlofferticket: 'Buy 1 Get 1 Movie Tickets on Paytm ',
    AccountsavingTitle: 'Savings Account  ',
    rate_of_interest: 10,
    joining_fee: 499,
    DebitCardTitle: 'Debit Card Facilities  ',
    min_bal_to_open_ac: 1000
  },
  {
    id: 2,
    bankName: 'HDFC',
    annual_fee: 222,
    rewards: 'Best of Rewards Cards',
    daily_txn_limit_online: 10000,
    card: 'Kotak Mahindra Savings Account',
    Personalcard: 'Personal Loans',
    avg_mon_bal: 10000,
    InterestRate: 'Interest Rate',
    image: '/assets/listingCradfilter.svg',
    logoimg: '/assets/footer-Logo.svg',
    helpimg: '/assets/help-circle.svg',
    cardLogo: '/assets/kotak-logo.svg',
    ratingtitle: 'BankSathi Rating',
    money: '₹ 300/-',
    based: ' Dining - Shopping - Movie',
    monthlybalance: 'Minimum monthly balance',
    none: 'None',
    future: 'Feature',
    shopping: 'Shopping, Rewards..',
    compare: 'Add to Compare',
    details: 'View Details',
    balanceOpenAcc: 'Minimum Balance to Open A/c',
    balanceOpendetail: '5000',
    InterestRatedetail: '4%',
    monthlybalancedetail: '50000',
    complimentary: 'Buy 1 Get 1 Movie Tickets on Paytm',
    sonyliv: 'Get 40% off on food delivery at Swiggy ',
    edge: '20% off at 4000+ partner restaurants in India',
    upto: 'Get Flat ₹600 off at AJIO, on minimum spends of ₹2000 ',
    restoff: '20% off at 4000+ partner restaurants in India',
    apllynow: 'Apply now',
    checkelig: 'Check Eligibility',
    offertype: 'reward Credit',
    rating: 4.9,
    atm_with_limit_fpm: '1000000',
    bankType: 'hdfc',
    features: 'Features',
    welcomeoffer: 'Welcome Offer',
    eligibledata: 'Eligible',
    wloffersony: 'SonyLiv Premium 1 year subscription worth ₹999 ',
    wlofferatoff: ' ₹ 600 off at AJIO, on minimum spends of ₹ 2000',
    wlofferswiggy: '40% off on Swiggy',
    wlofferairport: '4 Complimentary Airport Lounge Access',
    wlofferticket: 'Buy 1 Get 1 Movie Tickets on Paytm ',
    AccountsavingTitle: 'Savings Account  ',

    rate_of_interest: 10,
    joining_fee: 499,
    DebitCardTitle: 'Debit Card Facilities  ',
    min_bal_to_open_ac: 1000
  },
  {
    id: 3,
    bankName: 'ICICI',
    annual_fee: 1,
    rewards: 'Best of Rewards Cards',
    daily_txn_limit_online: 10000,
    card: 'Kotak Mahindra Savings Account',
    Personalcard: 'Personal Loans',
    avg_mon_bal: 3000,
    InterestRate: 'Interest Rate',
    image: '/assets/listingCradfilter.svg',
    logoimg: '/assets/footer-Logo.svg',
    helpimg: '/assets/help-circle.svg',
    cardLogo: '/assets/kotak-logo.svg',
    ratingtitle: 'BankSathi Rating',
    money: '₹ 300/-',
    based: ' Dining - Shopping - Movie',
    monthlybalance: 'Minimum monthly balance',
    none: 'None',
    future: 'Feature',
    shopping: 'Shopping, Rewards..',
    compare: 'Add to Compare',
    details: 'View Details',
    balanceOpenAcc: 'Minimum Balance to Open A/c',
    balanceOpendetail: '5000',
    InterestRatedetail: '4%',
    monthlybalancedetail: '50000',
    complimentary: 'Buy 1 Get 1 Movie Tickets on Paytm',
    sonyliv: 'Get 40% off on food delivery at Swiggy ',
    edge: '20% off at 4000+ partner restaurants in India',
    upto: 'Get Flat ₹600 off at AJIO, on minimum spends of ₹2000 ',
    restoff: '20% off at 4000+ partner restaurants in India',
    apllynow: 'Apply now',
    checkelig: 'Check Eligibility',
    offertype: 'reward Credit',
    rating: 4.9,
    atm_with_limit_fpm: '1000000',
    bankType: 'hdfc',
    features: 'Features',
    welcomeoffer: 'Welcome Offer',
    eligibledata: 'Eligible',
    wloffersony: 'SonyLiv Premium 1 year subscription worth ₹999 ',
    wlofferatoff: ' ₹ 600 off at AJIO, on minimum spends of ₹ 2000',
    wlofferswiggy: '40% off on Swiggy',
    wlofferairport: '4 Complimentary Airport Lounge Access',
    wlofferticket: 'Buy 1 Get 1 Movie Tickets on Paytm ',
    AccountsavingTitle: 'Savings Account  ',

    rate_of_interest: 10,
    joining_fee: 499,
    DebitCardTitle: 'Debit Card Facilities  ',
    min_bal_to_open_ac: 1000
  },
  {
    id: 4,
    bankName: 'ICICI',
    annual_fee: 1,
    rewards: 'Best of Rewards Cards',
    daily_txn_limit_online: 40000,
    card: 'Kotak Mahindra Savings Account',
    Personalcard: 'Personal Loans',
    avg_mon_bal: 30000,
    InterestRate: 'Interest Rate',
    image: '/assets/listingCradfilter.svg',
    logoimg: '/assets/footer-Logo.svg',
    helpimg: '/assets/help-circle.svg',
    cardLogo: '/assets/kotak-logo.svg',
    ratingtitle: 'BankSathi Rating',
    money: '₹ 300/-',
    based: ' Dining - Shopping - Movie',
    monthlybalance: 'Minimum monthly balance',
    none: 'None',
    future: 'Feature',
    shopping: 'Shopping, Rewards..',
    compare: 'Add to Compare',
    details: 'View Details',
    balanceOpenAcc: 'Minimum Balance to Open A/c',
    balanceOpendetail: '5000',
    InterestRatedetail: '4%',
    monthlybalancedetail: '50000',
    complimentary: 'Buy 1 Get 1 Movie Tickets on Paytm',
    sonyliv: 'Get 40% off on food delivery at Swiggy ',
    edge: '20% off at 4000+ partner restaurants in India',
    upto: 'Get Flat ₹600 off at AJIO, on minimum spends of ₹2000 ',
    restoff: '20% off at 4000+ partner restaurants in India',
    apllynow: 'Apply now',
    checkelig: 'Check Eligibility',
    offertype: 'reward Credit',
    rating: 4.9,
    atm_with_limit_fpm: '1000000',
    bankType: 'hdfc',
    features: 'Features',
    welcomeoffer: 'Welcome Offer',
    eligibledata: 'Eligible',
    wloffersony: 'SonyLiv Premium 1 year subscription worth ₹999 ',
    wlofferatoff: ' ₹ 600 off at AJIO, on minimum spends of ₹ 2000',
    wlofferswiggy: '40% off on Swiggy',
    wlofferairport: '4 Complimentary Airport Lounge Access',
    wlofferticket: 'Buy 1 Get 1 Movie Tickets on Paytm ',
    AccountsavingTitle: 'Savings Account  ',
    rate_of_interest: 6,
    joining_fee: 9,
    DebitCardTitle: 'Debit Card Facilities  ',
    min_bal_to_open_ac: 1000
  },
  {
    id: 5,
    bankName: 'ICICI',
    annual_fee: 1,
    rewards: 'Best of Rewards Cards',
    daily_txn_limit_online: 10000,
    card: 'Kotak Mahindra Savings Account',
    Personalcard: 'Personal Loans',
    avg_mon_bal: 30000,
    InterestRate: 'Interest Rate',
    image: '/assets/listingCradfilter.svg',
    logoimg: '/assets/footer-Logo.svg',
    helpimg: '/assets/help-circle.svg',
    cardLogo: '/assets/kotak-logo.svg',
    ratingtitle: 'BankSathi Rating',
    money: '₹ 300/-',
    based: ' Dining - Shopping - Movie',
    monthlybalance: 'Minimum monthly balance',
    none: 'None',
    future: 'Feature',
    shopping: 'Shopping, Rewards..',
    compare: 'Add to Compare',
    details: 'View Details',
    balanceOpenAcc: 'Minimum Balance to Open A/c',
    balanceOpendetail: '5000',
    InterestRatedetail: '4%',
    monthlybalancedetail: '50000',
    complimentary: 'Buy 1 Get 1 Movie Tickets on Paytm',
    sonyliv: 'Get 40% off on food delivery at Swiggy ',
    edge: '20% off at 4000+ partner restaurants in India',
    upto: 'Get Flat ₹600 off at AJIO, on minimum spends of ₹2000 ',
    restoff: '20% off at 4000+ partner restaurants in India',
    apllynow: 'Apply now',
    checkelig: 'Check Eligibility',
    offertype: 'reward Credit',
    rating: 4.9,
    atm_with_limit_fpm: '2000000',
    bankType: 'hdfc',
    features: 'Features',
    welcomeoffer: 'Welcome Offer',
    eligibledata: 'Eligible',
    wloffersony: 'SonyLiv Premium 1 year subscription worth ₹999 ',
    wlofferatoff: ' ₹ 600 off at AJIO, on minimum spends of ₹ 2000',
    wlofferswiggy: '40% off on Swiggy',
    wlofferairport: '4 Complimentary Airport Lounge Access',
    wlofferticket: 'Buy 1 Get 1 Movie Tickets on Paytm ',
    AccountsavingTitle: 'Savings Account  ',

    rate_of_interest: 10,
    joining_fee: 9,
    DebitCardTitle: 'Debit Card Facilities  ',
    min_bal_to_open_ac: 2000
  },
  {
    id: 6,
    bankName: 'ICICI',
    annual_fee: 1100,
    rewards: 'Best of Rewards Cards',
    daily_txn_limit_online: 10000,
    card: 'Kotak Mahindra Savings Account',
    Personalcard: 'Personal Loans',
    avg_mon_bal: 4000,
    InterestRate: 'Interest Rate',
    image: '/assets/listingCradfilter.svg',
    logoimg: '/assets/footer-Logo.svg',
    helpimg: '/assets/help-circle.svg',
    cardLogo: '/assets/kotak-logo.svg',
    ratingtitle: 'BankSathi Rating',
    money: '₹ 300/-',
    based: ' Dining - Shopping - Movie',
    monthlybalance: 'Minimum monthly balance',
    none: 'None',
    future: 'Feature',
    shopping: 'Shopping, Rewards..',
    compare: 'Add to Compare',
    details: 'View Details',
    balanceOpenAcc: 'Minimum Balance to Open A/c',
    balanceOpendetail: '5000',
    InterestRatedetail: '4%',
    monthlybalancedetail: '50000',
    complimentary: 'Buy 1100 Get 1 Movie Tickets on Paytm',
    sonyliv: 'Get 40% off on food delivery at Swiggy ',
    edge: '20% off at 4000+ partner restaurants in India',
    upto: 'Get Flat ₹600 off at AJIO, on minimum spends of ₹2000 ',
    restoff: '20% off at 4000+ partner restaurants in India',
    apllynow: 'Apply now',
    checkelig: 'Check Eligibility',
    offertype: 'reward Credit',
    rating: 4.9,
    atm_with_limit_fpm: '',
    bankType: 'hdfc',
    features: 'Features',
    welcomeoffer: 'Welcome Offer',
    eligibledata: 'Eligible',
    wloffersony: 'SonyLiv Premium 1 year subscription worth ₹999 ',
    wlofferatoff: ' ₹ 600 off at AJIO, on minimum spends of ₹ 2000',
    wlofferswiggy: '40% off on Swiggy',
    wlofferairport: '4 Complimentary Airport Lounge Access',
    wlofferticket: 'Buy 1 Get 1 Movie Tickets on Paytm ',
    AccountsavingTitle: 'Savings Account  ',

    rate_of_interest: 10,
    joining_fee: 499,
    DebitCardTitle: 'Debit Card Facilities  ',
    min_bal_to_open_ac: 4000
  },
  {
    id: 7,
    bankName: 'ICICI',
    annual_fee: 1,
    rewards: 'Best of Rewards Cards',
    daily_txn_limit_online: 2000,
    card: 'Kotak Mahindra Savings Account',
    Personalcard: 'Personal Loans',
    avg_mon_bal: 4000,
    InterestRate: 'Interest Rate',
    image: '/assets/listingCradfilter.svg',
    logoimg: '/assets/footer-Logo.svg',
    helpimg: '/assets/help-circle.svg',
    cardLogo: '/assets/kotak-logo.svg',
    ratingtitle: 'BankSathi Rating',
    money: '₹ 300/-',
    based: ' Dining - Shopping - Movie',
    monthlybalance: 'Minimum monthly balance',
    none: 'None',
    future: 'Feature',
    shopping: 'Shopping, Rewards..',
    compare: 'Add to Compare',
    details: 'View Details',
    balanceOpenAcc: 'Minimum Balance to Open A/c',
    balanceOpendetail: '5000',
    InterestRatedetail: '4%',
    monthlybalancedetail: '50000',
    complimentary: 'Buy 1 Get 1 Movie Tickets on Paytm',
    sonyliv: 'Get 40% off on food delivery at Swiggy ',
    edge: '20% off at 4000+ partner restaurants in India',
    upto: 'Get Flat ₹600 off at AJIO, on minimum spends of ₹2000 ',
    restoff: '20% off at 4000+ partner restaurants in India',
    apllynow: 'Apply now',
    checkelig: 'Check Eligibility',
    offertype: 'reward Credit',
    rating: 4.9,
    atm_with_limit_fpm: '',
    bankType: 'hdfc',
    features: 'Features',
    welcomeoffer: 'Welcome Offer',
    eligibledata: 'Eligible',
    wloffersony: 'SonyLiv Premium 1 year subscription worth ₹999 ',
    wlofferatoff: ' ₹ 600 off at AJIO, on minimum spends of ₹ 2000',
    wlofferswiggy: '40% off on Swiggy',
    wlofferairport: '4 Complimentary Airport Lounge Access',
    wlofferticket: 'Buy 1 Get 1 Movie Tickets on Paytm ',
    AccountsavingTitle: 'Savings Account  ',
    rate_of_interest: 6.5,
    joining_fee: 499,
    DebitCardTitle: 'Debit Card Facilities  ',
    min_bal_to_open_ac: 1000
  },
  {
    id: 8,
    bankName: 'ICICI',
    annual_fee: 200,
    rewards: 'Best of Rewards Cards',
    daily_txn_limit_online: 10000,
    card: 'Kotak Mahindra Savings Account',
    Personalcard: 'Personal Loans',
    avg_mon_bal: 0,
    InterestRate: 'Interest Rate',
    image: '/assets/listingCradfilter.svg',
    logoimg: '/assets/footer-Logo.svg',
    helpimg: '/assets/help-circle.svg',
    cardLogo: '/assets/kotak-logo.svg',
    ratingtitle: 'BankSathi Rating',
    money: '₹ 300/-',
    based: ' Dining - Shopping - Movie',
    monthlybalance: 'Minimum monthly balance',
    none: 'None',
    future: 'Feature',
    shopping: 'Shopping, Rewards..',
    compare: 'Add to Compare',
    details: 'View Details',
    balanceOpenAcc: 'Minimum Balance to Open A/c',
    balanceOpendetail: '5000',
    InterestRatedetail: '4%',
    monthlybalancedetail: '50000',
    complimentary: 'Buy 1 Get 1 Movie Tickets on Paytm',
    sonyliv: 'Get 40% off on food delivery at Swiggy ',
    edge: '20% off at 4000+ partner restaurants in India',
    upto: 'Get Flat ₹600 off at AJIO, on minimum spends of ₹2000 ',
    restoff: '20% off at 4000+ partner restaurants in India',
    apllynow: 'Apply now',
    checkelig: 'Check Eligibility',
    offertype: 'reward Credit',
    rating: 4.9,
    atm_with_limit_fpm: '',
    bankType: 'hdfc',
    features: 'Features',
    welcomeoffer: 'Welcome Offer',
    eligibledata: 'Eligible',
    wloffersony: 'SonyLiv Premium 1 year subscription worth ₹999 ',
    wlofferatoff: ' ₹ 600 off at AJIO, on minimum spends of ₹ 2000',
    wlofferswiggy: '40% off on Swiggy',
    wlofferairport: '4 Complimentary Airport Lounge Access',
    wlofferticket: 'Buy 1 Get 1 Movie Tickets on Paytm ',
    AccountsavingTitle: 'Savings Account  ',

    rate_of_interest: 10,
    joining_fee: 499,
    DebitCardTitle: 'Debit Card Facilities  ',
    min_bal_to_open_ac: 10000
  },
  {
    id: 9,
    bankName: 'ICICI',
    annual_fee: 22220,
    rewards: 'Best of Rewards Cards',
    daily_txn_limit_online: 1000000,
    card: 'Kotak Mahindra Savings Account',
    Personalcard: 'Personal Loans',
    avg_mon_bal: 100000,
    InterestRate: 'Interest Rate',
    image: '/assets/listingCradfilter.svg',
    logoimg: '/assets/footer-Logo.svg',
    helpimg: '/assets/help-circle.svg',
    cardLogo: '/assets/kotak-logo.svg',
    ratingtitle: 'BankSathi Rating',
    money: '₹ 300/-',
    based: ' Dining - Shopping - Movie',
    monthlybalance: 'Minimum monthly balance',
    none: 'None',
    future: 'Feature',
    shopping: 'Shopping, Rewards..',
    compare: 'Add to Compare',
    details: 'View Details',
    balanceOpenAcc: 'Minimum Balance to Open A/c',
    balanceOpendetail: '5000',
    InterestRatedetail: '4%',
    monthlybalancedetail: '50000',
    complimentary: 'Buy 1 Get 1 Movie Tickets on Paytm',
    sonyliv: 'Get 40% off on food delivery at Swiggy ',
    edge: '20% off at 4000+ partner restaurants in India',
    upto: 'Get Flat ₹600 off at AJIO, on minimum spends of ₹2000 ',
    restoff: '20% off at 4000+ partner restaurants in India',
    apllynow: 'Apply now',
    checkelig: 'Check Eligibility',
    offertype: 'reward Credit',
    rating: 4.9,
    atm_with_limit_fpm: '200',
    bankType: 'hdfc',
    features: 'Features',
    welcomeoffer: 'Welcome Offer',
    eligibledata: 'Eligible',
    wloffersony: 'SonyLiv Premium 1 year subscription worth ₹999 ',
    wlofferatoff: ' ₹ 600 off at AJIO, on minimum spends of ₹ 2000',
    wlofferswiggy: '40% off on Swiggy',
    wlofferairport: '4 Complimentary Airport Lounge Access',
    wlofferticket: 'Buy 1 Get 1 Movie Tickets on Paytm ',
    AccountsavingTitle: 'Savings Account  ',

    rate_of_interest: 10,
    joining_fee: 499,
    DebitCardTitle: 'Debit Card Facilities  ',
    min_bal_to_open_ac: 1000
  },
  {
    id: 10,
    bankName: 'AXIS',
    annual_fee: 1,
    rewards: 'Best of Rewards Cards',
    daily_txn_limit_online: 10000,
    card: 'Kotak Mahindra Savings Account',
    Personalcard: 'Personal Loans',
    avg_mon_bal: 1000,
    InterestRate: 'Interest Rate',
    image: '/assets/listingCradfilter.svg',
    logoimg: '/assets/footer-Logo.svg',
    helpimg: '/assets/help-circle.svg',
    cardLogo: '/assets/kotak-logo.svg',
    ratingtitle: 'BankSathi Rating',
    money: '₹ 300/-',
    based: ' Dining - Shopping - Movie',
    monthlybalance: 'Minimum monthly balance',
    none: 'None',
    future: 'Feature',
    shopping: 'Shopping, Rewards..',
    compare: 'Add to Compare',
    details: 'View Details',
    balanceOpenAcc: 'Minimum Balance to Open A/c',
    balanceOpendetail: '5000',
    InterestRatedetail: '4%',
    monthlybalancedetail: '50000',
    complimentary: 'Buy 1 Get 1 Movie Tickets on Paytm',
    sonyliv: 'Get 40% off on food delivery at Swiggy ',
    edge: '20% off at 4000+ partner restaurants in India',
    upto: 'Get Flat ₹600 off at AJIO, on minimum spends of ₹2000 ',
    restoff: '20% off at 4000+ partner restaurants in India',
    apllynow: 'Apply now',
    checkelig: 'Check Eligibility',
    offertype: 'reward Credit',
    rating: 4.9,
    atm_with_limit_fpm: '102290',
    bankType: 'hdfc',
    features: 'Features',
    welcomeoffer: 'Welcome Offer',
    eligibledata: 'Eligible',
    wloffersony: 'SonyLiv Premium 1 year subscription worth ₹999 ',
    wlofferatoff: ' ₹ 600 off at AJIO, on minimum spends of ₹ 2000',
    wlofferswiggy: '40% off on Swiggy',
    wlofferairport: '4 Complimentary Airport Lounge Access',
    wlofferticket: 'Buy 1 Get 1 Movie Tickets on Paytm ',
    rate_of_interest: 10,
    joining_fee: 499,
    DebitCardTitle: 'Debit Card Facilities  ',
    min_bal_to_open_ac: 100
  },
  {
    id: 11,
    bankName: 'SBI',
    annual_fee: 2,
    rewards: 'Best of Rewards Cards',
    daily_txn_limit_online: 20000,
    card: 'Kotak Mahindra Savings Account',
    Personalcard: 'Personal Loans',
    avg_mon_bal: 100000,
    InterestRate: 'Interest Rate',
    image: '/assets/listingCradfilter.svg',
    logoimg: '/assets/footer-Logo.svg',
    helpimg: '/assets/help-circle.svg',
    cardLogo: '/assets/kotak-logo.svg',
    ratingtitle: 'BankSathi Rating',
    money: '₹ 300/-',
    based: ' Dining - Shopping - Movie',
    monthlybalance: 'Minimum monthly balance',
    none: 'None',
    future: 'Feature',
    shopping: 'Shopping, Rewards..',
    compare: 'Add to Compare',
    details: 'View Details',
    balanceOpenAcc: 'Minimum Balance to Open A/c',
    balanceOpendetail: '5000',
    InterestRatedetail: '4%',
    monthlybalancedetail: '50000',
    complimentary: 'Buy 1 Get 1 Movie Tickets on Paytm',
    sonyliv: 'Get 40% off on food delivery at Swiggy ',
    edge: '20% off at 4000+ partner restaurants in India',
    upto: 'Get Flat ₹600 off at AJIO, on minimum spends of ₹2000 ',
    restoff: '20% off at 4000+ partner restaurants in India',
    apllynow: 'Apply now',
    checkelig: 'Check Eligibility',
    offertype: 'reward Credit',
    rating: 4.9,
    atm_with_limit_fpm: '',
    bankType: 'hdfc',
    features: 'Features',
    welcomeoffer: 'Welcome Offer',
    eligibledata: 'Eligible',
    wloffersony: 'SonyLiv Premium 1 year subscription worth ₹999 ',
    wlofferatoff: ' ₹ 600 off at AJIO, on minimum spends of ₹ 2000',
    wlofferswiggy: '40% off on Swiggy',
    wlofferairport: '4 Complimentary Airport Lounge Access',
    wlofferticket: 'Buy 1 Get 1 Movie Tickets on Paytm ',
    AccountsavingTitle: 'Savings Account  ',
    rate_of_interest: 10,
    joining_fee: 0,
    DebitCardTitle: 'Debit Card Facilities  ',
    min_bal_to_open_ac: 1000
  },
  {
    id: 12,
    bankName: 'ICICI',
    annual_fee: 1,
    rewards: 'Best of Rewards Cards',
    daily_txn_limit_online: 20000,
    card: 'Kotak Mahindra Savings Account',
    Personalcard: 'Personal Loans',
    avg_mon_bal: 10000,
    InterestRate: 'Interest Rate',
    image: '/assets/listingCradfilter.svg',
    logoimg: '/assets/footer-Logo.svg',
    helpimg: '/assets/help-circle.svg',
    cardLogo: '/assets/kotak-logo.svg',
    ratingtitle: 'BankSathi Rating',
    money: '₹ 300/-',
    based: ' Dining - Shopping - Movie',
    monthlybalance: 'Minimum monthly balance',
    none: 'None',
    future: 'Feature',
    shopping: 'Shopping, Rewards..',
    compare: 'Add to Compare',
    details: 'View Details',
    balanceOpenAcc: 'Minimum Balance to Open A/c',
    balanceOpendetail: '5000',
    InterestRatedetail: '4%',
    monthlybalancedetail: '50000',
    complimentary: 'Buy 1 Get 1 Movie Tickets on Paytm',
    sonyliv: 'Get 40% off on food delivery at Swiggy ',
    edge: '20% off at 4000+ partner restaurants in India',
    upto: 'Get Flat ₹600 off at AJIO, on minimum spends of ₹2000 ',
    restoff: '20% off at 4000+ partner restaurants in India',
    apllynow: 'Apply now',
    checkelig: 'Check Eligibility',
    offertype: 'reward Credit',
    rating: 4.9,
    atm_with_limit_fpm: '222344',
    bankType: 'hdfc',
    features: 'Features',
    welcomeoffer: 'Welcome Offer',
    eligibledata: 'Eligible',
    wloffersony: 'SonyLiv Premium 1 year subscription worth ₹999 ',
    wlofferatoff: ' ₹ 600 off at AJIO, on minimum spends of ₹ 2000',
    wlofferswiggy: '40% off on Swiggy',
    wlofferairport: '4 Complimentary Airport Lounge Access',
    wlofferticket: 'Buy 1 Get 1 Movie Tickets on Paytm ',
    AccountsavingTitle: 'Savings Account  ',
    rate_of_interest: 7.5,
    joining_fee: 0,
    DebitCardTitle: 'Debit Card Facilities  ',
    min_bal_to_open_ac: 1000
  },
  {
    id: 13,
    bankName: 'BOB',
    annual_fee: 1,
    rewards: 'Best of Rewards Cards',
    daily_txn_limit_online: 1000000,
    card: 'Kotak Mahindra Savings Account',
    Personalcard: 'Personal Loans',
    avg_mon_bal: 13000,
    InterestRate: 'Interest Rate',
    image: '/assets/listingCradfilter.svg',
    logoimg: '/assets/footer-Logo.svg',
    helpimg: '/assets/help-circle.svg',
    cardLogo: '/assets/kotak-logo.svg',
    ratingtitle: 'BankSathi Rating',
    money: '₹ 300/-',
    based: ' Dining - Shopping - Movie',
    monthlybalance: 'Minimum monthly balance',
    none: 'None',
    future: 'Feature',
    shopping: 'Shopping, Rewards..',
    compare: 'Add to Compare',
    details: 'View Details',
    balanceOpenAcc: 'Minimum Balance to Open A/c',
    balanceOpendetail: '5000',
    InterestRatedetail: '4%',
    monthlybalancedetail: '50000',
    complimentary: 'Buy 1 Get 1 Movie Tickets on Paytm',
    sonyliv: 'Get 40% off on food delivery at Swiggy ',
    edge: '20% off at 4000+ partner restaurants in India',
    upto: 'Get Flat ₹600 off at AJIO, on minimum spends of ₹2000 ',
    restoff: '20% off at 4000+ partner restaurants in India',
    apllynow: 'Apply now',
    checkelig: 'Check Eligibility',
    offertype: 'reward Credit',
    rating: 4.9,
    atm_with_limit_fpm: '555555',
    bankType: 'hdfc',
    features: 'Features',
    welcomeoffer: 'Welcome Offer',
    eligibledata: 'Eligible',
    wloffersony: 'SonyLiv Premium 1 year subscription worth ₹999 ',
    wlofferatoff: ' ₹ 600 off at AJIO, on minimum spends of ₹ 2000',
    wlofferswiggy: '40% off on Swiggy',
    wlofferairport: '4 Complimentary Airport Lounge Access',
    wlofferticket: 'Buy 1 Get 1 Movie Tickets on Paytm ',
    AccountsavingTitle: 'Savings Account  ',

    rate_of_interest: 7.5,
    joining_fee: 0,
    DebitCardTitle: 'Debit Card Facilities  ',
    min_bal_to_open_ac: 0
  }
]
